<?php

/*********************************************************************
* Extension configuration file for ext "externalimport_tut".
*
* Generated by ext 03-08-2016 19:39 UTC
*
* https://github.com/t3elmar/Ext
*********************************************************************/

$EM_CONF[$_EXTKEY] = array (
  'title' => 'External Import Tutorial',
  'description' => 'Tutorial for the External Import extension. Contains the manual and the necessary files.',
  'category' => 'example',
  'author' => 'Francois Suter (Cobweb)',
  'author_email' => 'typo3@cobweb.ch',
  'state' => 'stable',
  'uploadfolder' => 0,
  'createDirs' => '',
  'clearCacheOnLoad' => 1,
  'author_company' => '',
  'version' => '2.1.1',
  'constraints' =>
  array (
    'depends' =>
    array (
      'external_import' => '4.0.0-0.0.0',
      'svconnector_csv' => '2.2.1-0.0.0',
      'svconnector_feed' => '2.2.1-0.0.0',
      'news' => '6.2.0-0.0.0',
      'typo3' => '7.6.0-8.99.99',
    ),
    'conflicts' =>
    array (
    ),
    'suggests' =>
    array (
      'devlog' => '',
    ),
  ),
);

?>